import { createFileRoute } from "@tanstack/react-router";
import { AlertTriangle, Camera, CheckCircle2, Headphones, ImagePlus, Leaf, RotateCcw } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { toast } from "sonner";
import { PageIntro } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { DISCLAIMER, HISTORY_KEY, speakTamil, type HistoryItem } from "@/lib/agri-data";
import chilliLeaf from "@/assets/chilli-leaf-demo.svg";

export const Route = createFileRoute("/disease-detection")({ head:()=>({meta:[{title:"பயிர் நோய் கண்டறிதல் — AgriTamil AI"},{name:"description",content:"பயிர் படத்தைப் பதிவேற்றி விளக்கமான மாதிரி நோய் பகுப்பாய்வைப் பார்க்கவும்."},{property:"og:title",content:"பயிர் நோய் கண்டறிதல் — AgriTamil AI"},{property:"og:description",content:"தமிழில் ஆரம்பகட்ட மாதிரி பயிர் வழிகாட்டுதல்."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}), component: DiseasePage });

function DiseasePage(){
 const [image,setImage]=useState(chilliLeaf); const [state,setState]=useState<"ready"|"analyzing"|"done">("done"); const [progress,setProgress]=useState(89); const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{ if(state!=="analyzing") return; setProgress(10); const timer=window.setInterval(()=>setProgress(v=>Math.min(v+18,89)),180); const done=window.setTimeout(()=>{window.clearInterval(timer);setProgress(89);setState("done"); const records=JSON.parse(localStorage.getItem(HISTORY_KEY)||"[]") as HistoryItem[]; if(!records.some(r=>r.id==="latest-analysis")) localStorage.setItem(HISTORY_KEY,JSON.stringify([{id:"latest-analysis",date:new Date().toLocaleDateString("ta-IN"),crop:"மிளகாய்",question:"பயிர் படப் பகுப்பாய்வு",result:"இலை நோய் (மாதிரி)",confidence:89,recommendation:"பாதிக்கப்பட்ட இலைகளை அகற்றி, காற்றோட்டத்தை அதிகரித்து, அதிக நீரைத் தவிர்க்கவும்.",image},...records]));},1300); return()=>{window.clearInterval(timer);window.clearTimeout(done)};},[state,image]);
 const choose=(file?:File)=>{if(!file)return;if(!file.type.match(/^image\/(jpeg|png)$/)){toast.error("JPG, JPEG அல்லது PNG படம் மட்டும்");return;}const reader=new FileReader();reader.onload=()=>{if(typeof reader.result==="string"){setImage(reader.result);setState("ready");setProgress(0)}};reader.readAsDataURL(file)};
 return <div className="page-wrap"><PageIntro eyebrow="Demo crop vision" title="பயிர் நோய் கண்டறிதல்" description="தெளிவான இலை அல்லது பயிர் படத்தைச் சேர்க்கவும். காண்பிக்கப்படும் முடிவு விளக்கத்திற்கான மாதிரி மட்டுமே."/><div className="grid gap-6 lg:grid-cols-[1fr_1.05fr]"><section className="surface-card overflow-hidden"><div className="relative aspect-[4/3] bg-muted"><img src={image} width={1200} height={900} alt="புள்ளிகளுடன் கூடிய மிளகாய் இலை மாதிரி" className="h-full w-full object-cover"/>{state==="analyzing"&&<div className="absolute inset-0 grid place-items-center bg-forest/70 text-center text-forest-foreground"><div><Leaf className="mx-auto size-12 animate-pulse"/><p className="mt-4 font-bold">படத்தை பகுப்பாய்வு செய்கிறது...</p></div></div>}<span className="absolute left-3 top-3 rounded-full bg-background/95 px-3 py-1 text-xs font-bold text-primary">மாதிரி மிளகாய் இலை</span></div><div className="p-5"><div className="grid grid-cols-2 gap-3"><Button variant="outline" className="h-12" onClick={()=>input.current?.click()}><ImagePlus/> படம் தேர்வு</Button><Button variant="outline" className="h-12" onClick={()=>input.current?.click()}><Camera/> கேமரா</Button></div><input ref={input} className="hidden" type="file" accept="image/png,image/jpeg" capture="environment" onChange={e=>choose(e.target.files?.[0])}/><Button className="mt-3 h-12 w-full" onClick={()=>setState("analyzing")} disabled={state==="analyzing"}><Leaf/> {state==="analyzing"?"சோதிக்கிறது...":"இந்தப் பயிரைச் சோதிக்கவும்"}</Button><p className="mt-3 text-center text-xs text-muted-foreground">JPG, JPEG, PNG · தெளிவான இயற்கை வெளிச்சம் சிறந்தது</p></div></section>
 <section className="surface-card p-5 sm:p-7"><div className="flex items-start justify-between gap-3"><div><span className="eyebrow">Demo AI Result</span><h2 className="mt-3 text-2xl font-extrabold">மாதிரி பகுப்பாய்வு</h2></div><Button variant="ghost" size="icon" onClick={()=>{setImage(chilliLeaf);setState("done");setProgress(89)}} aria-label="மாதிரியை மீட்டமை"><RotateCcw/></Button></div><div className="mt-6"><div className="mb-2 flex justify-between text-sm"><span>நம்பகத்தன்மை (illustrative)</span><b className="text-primary">{progress}%</b></div><Progress value={progress}/></div>{state==="done"?<div className="mt-7 space-y-5 gentle-rise"><div className="grid grid-cols-2 gap-3"><div className="rounded-lg bg-secondary p-4"><span className="text-xs text-muted-foreground">பயிர்</span><p className="mt-1 font-bold">🌶️ மிளகாய்</p></div><div className="rounded-lg bg-accent/35 p-4"><span className="text-xs text-muted-foreground">சாத்தியமான பிரச்சனை</span><p className="mt-1 font-bold">இலை நோய்</p></div></div><div><h3 className="flex items-center gap-2 font-bold"><CheckCircle2 className="size-5 text-primary"/> எளிய பரிந்துரை</h3><ol className="mt-3 space-y-2 text-sm leading-6 text-muted-foreground"><li>1. பாதிக்கப்பட்ட இலைகளை அகற்றி தனியே அப்புறப்படுத்துங்கள்.</li><li>2. செடிகளுக்கு இடையே காற்றோட்டத்தை அதிகரிக்கவும்.</li><li>3. இலை மேல் நீர் படாமல் வேர் பகுதியில் மட்டும் நீர் பாய்ச்சவும்.</li><li>4. மேலும் பரவினால் உள்ளூர் வேளாண் நிபுணரை அணுகவும்.</li></ol></div><Button variant="outline" onClick={()=>speakTamil("மிளகாய் செடியில் இலை நோய் இருப்பதற்கான அறிகுறிகள் காணப்படுகின்றன. பாதிக்கப்பட்ட இலைகளை அகற்றி, காற்றோட்டத்தை அதிகரிக்கவும்.")}><Headphones/> பரிந்துரையைக் கேட்க</Button></div>:<div className="mt-14 text-center text-sm text-muted-foreground">{state==="ready"?"பகுப்பாய்வு தொடங்க பொத்தானை அழுத்துங்கள்.":"படத்தின் நிறம் மற்றும் இலை அறிகுறிகள் பரிசோதிக்கப்படுகின்றன."}</div>}<div className="mt-7 flex gap-3 rounded-lg border border-accent bg-accent/15 p-4"><AlertTriangle className="mt-0.5 size-5 shrink-0 text-accent-foreground"/><div><b className="text-sm">முக்கிய அறிவிப்பு</b><p className="mt-1 text-xs leading-5 text-muted-foreground">{DISCLAIMER} இந்த முடிவு விளக்கத்திற்கானது; உறுதியான நோய் கண்டறிதல் அல்ல.</p></div></div></section></div></div>
}